apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: Python app that display some informations about your API.
  annotations:
   github.com/project-slug: igor-gouvea/${{ values.app_name }}
   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: production
